Repository soen6431-winter25/OpenTracksW25, pull requests merged in 2025-03, with the labels that each got.

#41 Duplicate refactoring: define a Pace class instead of two separate cl…
  src/main/java/de/dennisguse/opentracks/viewmodels/GenericStatisticsViewHolder.java
  src/main/java/de/dennisguse/opentracks/viewmodels/Mapping.java
Labels: Group 6, technical debt

#46 Refactor TrackFileFormat: Remove Duplicate Enum Logic for KMZ Formats
  src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
Labels: Group 6, C2

#47 Removes code duplication of setSpeed and setPace methods
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsAdapter.java
Labels: Group 6, technical debt, C2

#50 Removes code clones for speed and pace related classes
  src/main/java/de/dennisguse/opentracks/viewmodels/GenericStatisticsViewHolder.java
Labels: Group 6, technical debt, C2

#57 adds updateUI method to reduce code duplication
  src/main/java/de/dennisguse/opentracks/viewmodels/SensorStatisticsViewHolder.java
Labels: Group 6, technical debt, C2

#70 Remove software vulnerabilities db.update()
  src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java
Labels: Group 6, C3, Software Vulnerability

#73 Remove software vulnerabilities: SQL Injection in db.update() #82
  src/main/java/de/dennisguse/opentracks/data/CustomContentProvider.java
Labels: Group 6, C3, Software Vulnerability
